# Writes build_info.h: the version and commit the build came from, for the menu, `x4vr version`,
# the bug report and the mod's log. Run at every build (linux/CMakeLists.txt, target
# x4vr_build_info), so a `git pull` and rebuild never reports the old commit; the header is only
# rewritten when it changes, so an unchanged checkout rebuilds nothing.
# The version is `git describe --dirty --always`: the nearest annotated tag (a release), and for a
# build after it the commits since and the commit, "-dirty" with uncommitted changes:
#   v0.5.0                         the release itself
#   v0.5.0-3-gdc86c67              3 commits after it
#   v0.5.0-3-gdc86c67-dirty        the same with local changes
#   dc86c67                        no annotated tag in its history
# -DROOT=<source folder> -DOUT=<header>; for a build without git (Nix, which reads them from .git):
# -DGIT_COMMIT=, -DGIT_DESCRIBE=. Without either: "unknown".
function(git out)
  execute_process(COMMAND git -C ${ROOT} ${ARGN} OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET
                  RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    set(value "")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()
# As a C string literal's contents.
function(c_string out text)
  string(REPLACE "\\" "\\\\" text "${text}")
  string(REPLACE "\"" "\\\"" text "${text}")
  string(REPLACE "\n" "\\n" text "${text}")
  set(${out} "${text}" PARENT_SCOPE)
endfunction()

git(commit rev-parse HEAD)
set(changed "")
set(date "")
set(subject "")
set(recent "")
if(NOT commit AND GIT_COMMIT)
  set(commit "${GIT_COMMIT}")
  set(build "${GIT_DESCRIBE} (Nix)")
elseif(commit)
  git(build describe --dirty --always)
  git(date log -1 --format=%cd --date=format:%Y-%m-%d\ %H:%M)
  git(subject log -1 --format=%s)
  git(changed status --porcelain --untracked-files=no)
  git(recent log -15 --format=%h\ %cd\ %s --date=short)
  string(REGEX REPLACE "(^|\n) ?[A-Z?]+ +" "\\1" changed "${changed}")
  string(REPLACE "\n" ", " changed "${changed}")
else()
  set(commit "unknown")
  set(build "unknown")
endif()
foreach(name build commit date subject changed recent)
  c_string(${name} "${${name}}")
endforeach()
set(text "// Generated by linux/build_info.cmake at build time.
#pragma once
#define X4VR_BUILD \"${build}\"
#define X4VR_COMMIT \"${commit}\"
#define X4VR_COMMIT_DATE \"${date}\"
#define X4VR_COMMIT_SUBJECT \"${subject}\"
#define X4VR_CHANGED_FILES \"${changed}\"
#define X4VR_RECENT_COMMITS \"${recent}\"
")
set(old "")
if(EXISTS ${OUT})
  file(READ ${OUT} old)
endif()
if(NOT old STREQUAL text)
  file(WRITE ${OUT} "${text}")
endif()
